version: "3.7"
services:
  webthings-server:
    image: kupcimat/webthings-server
    devices:
      - "/dev/serial/by-id/usb-Arduino_LLC_Arduino_Leonardo-if00:/dev/serial/arduino"
    network_mode: host
    restart: always
